server:
  address: 127.0.0.1
  port: 8080
spring:
  application:
    name: Moments
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
  sql:
    init:
      schema-locations:
      - classpath:schema.sql
      mode: always
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./Moments;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1
  data:
    rest:
      detection-strategy: annotated
  mail:
    host: smtp.example.com
    username: user
    password: password
    protocol: smtp
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  profiles:
    active:
    - dev
moments:
  serviceBasePath: http://127.0.0.1:8080
  auth:
    jwtSecret: momentsSecretKey
    jwtExpirationMs: 100000
    jwtRefreshExpirationMs: 600000
  security:
    trustedClients: >
      http://127.0.0.1:4200,
      http://192.168.1.114:4200
  discord:
    botToken: mydiscordbottoken
    channelID: 01234567890
    postReferenceLink: http://127.0.0.1:4200/post/{id}
    defaultAvatarLink: http://127.0.0.1:8080/img/default_avatar.png
  mail:
    accountActivationFromID: account@example.com
    passwordResetFromID: account@example.com
logging:
  file:
    name: moments.log